/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button2_click1(GButton source, GEvent event) { //_CODE_:lvl1:275263:
  level1=true;
  main=false;
  lvl1.setVisible(false);
} //_CODE_:lvl1:275263:

public void button2_click2(GButton source, GEvent event) { //_CODE_:store:985622:
  mark=true;

} //_CODE_:store:985622:

public void button2_click3(GButton source, GEvent event) { //_CODE_:buy1:221459:

  if (grid.coins>market.price1) {
    character=1;
    grid.coins-=market.price1;
  } 
  
} //_CODE_:buy1:221459:

public void button2_click4(GButton source, GEvent event) { //_CODE_:choose1:854496:
  println("choose1");
  character=1;
} //_CODE_:choose1:854496:

public void button2_click5(GButton source, GEvent event) { //_CODE_:pause:822284:
  pauseframe=true;
} //_CODE_:pause:822284:

public void button2_click6(GButton source, GEvent event) { //_CODE_:resume:361166:
  reSume=true;
} //_CODE_:resume:361166:

public void button2_click7(GButton source, GEvent event) { //_CODE_:next:283266:
  secondframe=true;
} //_CODE_:next:283266:

public void button2_click8(GButton source, GEvent event) { //_CODE_:shopback:229121:
  secondframe=true;
  mark=false;
  buy1.setVisible(false);
} //_CODE_:shopback:229121:

public void button2_click9(GButton source, GEvent event) { //_CODE_:backlvl1:715715:
 main=true;
 lost=false;
 backlvl1.setVisible(false);
} //_CODE_:backlvl1:715715:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  lvl1 = new GButton(this, 385, 529, 131, 49);
  lvl1.setIcon("LEVEL1.png", 1, GAlign.EAST, GAlign.RIGHT, GAlign.MIDDLE);
  lvl1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  lvl1.addEventHandler(this, "button2_click1");
  store = new GButton(this, 6, 6, 49, 58);
  store.setIcon("store.png", 1, GAlign.EAST, GAlign.RIGHT, GAlign.MIDDLE);
  store.addEventHandler(this, "button2_click2");
  buy1 = new GButton(this, 100, 162, 80, 30);
  buy1.setText("BUY");
  buy1.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  buy1.addEventHandler(this, "button2_click3");
  choose1 = new GButton(this, 99, 193, 80, 30);
  choose1.setText("CHOOSE");
  choose1.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  choose1.addEventHandler(this, "button2_click4");
  pause = new GButton(this, 135, 11, 47, 37);
  pause.setIcon("pauseb.png", 1, GAlign.EAST, GAlign.RIGHT, GAlign.MIDDLE);
  pause.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  pause.addEventHandler(this, "button2_click5");
  resume = new GButton(this, 278, 403, 386, 167);
  resume.setIcon("resume.png", 1, GAlign.EAST, GAlign.RIGHT, GAlign.MIDDLE);
  resume.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  resume.addEventHandler(this, "button2_click6");
  next = new GButton(this, 813, 865, 80, 30);
  next.setText("NEXT");
  next.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  next.addEventHandler(this, "button2_click7");
  shopback = new GButton(this, 2, 867, 80, 30);
  shopback.setText("back");
  shopback.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  shopback.addEventHandler(this, "button2_click8");
  backlvl1 = new GButton(this, 59, 819, 80, 30);
  backlvl1.setText("BACK");
  backlvl1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  backlvl1.addEventHandler(this, "button2_click9");
}

// Variable declarations 
// autogenerated do not edit
GButton lvl1; 
GButton store; 
GButton buy1; 
GButton choose1; 
GButton pause; 
GButton resume; 
GButton next; 
GButton shopback; 
GButton backlvl1; 
